# Generated by Django 5.1.7 on 2025-03-19 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_file', models.FileField(help_text='PDF de la réponse étudiante', upload_to='submissions/')),
                ('grade', models.FloatField(blank=True, help_text='Note sur 20', null=True)),
                ('feedback', models.TextField(blank=True, help_text='Feedback détaillé', null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, help_text='Date de soumission')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='exercises.exercise')),
            ],
        ),
    ]
