# Generated by Django 5.1.7 on 2025-03-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Titre de l'exercice", max_length=200)),
                ('description', models.TextField(help_text="Énoncé de l'exercice")),
                ('correction_file', models.FileField(help_text='PDF de correction', upload_to='corrections/')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date de création')),
            ],
        ),
    ]
